WARNING_PERSONAL_INFO_BLOCKED = "PERSONAL_INFO_BLOCKED"
WARNING_ABUSIVE_LANGUAGE_BLOCKED = "ABUSIVE_LANGUAGE_BLOCKED"
WARNING_CRISIS_LANGUAGE_DETECTED = "CRISIS_LANGUAGE_DETECTED"
WARNING_BANNED = "BANNED"
WARNING_RATE_LIMITED = "RATE_LIMITED"

ERROR_INVALID_JSON = "INVALID_JSON"
ERROR_UNKNOWN_TYPE = "UNKNOWN_TYPE"
ERROR_MESSAGE_TOO_LARGE = "MESSAGE_TOO_LARGE"
ERROR_INVALID_SESSION = "INVALID_SESSION"

SYSTEM_SESSION_ENDED = "SESSION_ENDED"
SYSTEM_SEEKER_LEFT = "SEEKER_LEFT"
SYSTEM_VOLUNTEER_LEFT = "VOLUNTEER_LEFT"
SYSTEM_SESSION_CANCELLED = "SESSION_CANCELLED"
SYSTEM_NO_VOLUNTEER_AVAILABLE = "NO_VOLUNTEER_AVAILABLE"
SYSTEM_CRISIS_RESOURCES = "CRISIS_RESOURCES"

WARNING_MESSAGES = {
    WARNING_PERSONAL_INFO_BLOCKED: "Personal information was blocked for safety.",
    WARNING_ABUSIVE_LANGUAGE_BLOCKED: "Abusive language was blocked.",
    WARNING_CRISIS_LANGUAGE_DETECTED: "Crisis-related language detected.",
    WARNING_BANNED: "You have been banned from the service.",
    WARNING_RATE_LIMITED: "You are sending messages too quickly.",
}

ERROR_MESSAGES = {
    ERROR_INVALID_JSON: "Invalid JSON payload.",
    ERROR_UNKNOWN_TYPE: "Unknown message type.",
    ERROR_MESSAGE_TOO_LARGE: "Message exceeds size limit.",
    ERROR_INVALID_SESSION: "Session is no longer active.",
}
